ansible_connection: httpapi
ansible_network_os: eos
ansible_user: cvpadmin
ansible_ssh_pass: arista123
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
timezone: America/Toronto
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$LJcUms0WZ9UyskIF$b6jUZMJmruk95uA0GPood4z4Tgb2aHKqnRhm7HyHl3kjsgE6mA5.V3W/vwl16WeICFvWWz1vkU1zQET0CbILG0
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$pWE0vYbIJTmV0ZWc$nIrbLNYS3pIgpFj9vuzkchwyA19betlJZjWR.KE95GHwOALliiUUAu92JUWg9jQ12Yd3.aTQmWf.gRe2VNo2Y.
cvp_instance_ip: 172.30.30.252
cvp_ingestauth_key: arista
mgmt_gateway: 172.30.30.1
mgmt_vrf_routing: false
mgmt_interface: Management1
mgmt_interface_vrf: mgmt
mgmt_destination_networks:
- 0.0.0.0/0
dns_domain: homelab.io
name_servers:
- 172.30.30.6
- 1.1.1.1
ntp_servers:
- time.google.com iburst
fabric_name: DC_FABRIC
underlay_p2p_network_summary: 10.10.100.0/24
overlay_loopback_network_summary: 192.168.100.0/24
vtep_loopback_network_summary: 192.168.101.0/24
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: AQQvKeimxJu+uGQ/yYvv9w==
  EVPN_OVERLAY_PEERS:
    password: q+VNViP5i4rVjW1cxFv2wA==
spine:
  platform: vEOS-LAB
  bgp_as: 65100
  leaf_as_range: 65101-65132
  nodes:
    DC-SPINE1:
      id: 1
      mgmt_ip: 172.30.30.211/24
    DC-SPINE2:
      id: 2
      mgmt_ip: 172.30.30.212/24
l3leaf:
  defaults:
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    bgp_as: 65000
    spines:
    - DC-SPINE1
    - DC-SPINE2
    uplink_to_spine_interfaces:
    - Ethernet1
    - Ethernet2
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    DC_LEAF1:
      bgp_as: 65101
      filter:
        tenants:
        - Tenant_blue
        - Tenant_green
        tags:
        - blue_compute
        - green_compute
        - green_storage
      nodes:
        DC-LEAF1:
          id: 1
          mgmt_ip: 172.30.30.213/24
          spine_interfaces:
          - Ethernet1
          - Ethernet1
    DC_LEAF2:
      bgp_as: 65102
      filter:
        tenants:
        - Tenant_blue
        - Tenant_green
        tags:
        - blue_compute
        - green_compute
        - green_storage
      nodes:
        DC-LEAF2:
          id: 2
          mgmt_ip: 172.30.30.214/24
          spine_interfaces:
          - Ethernet2
          - Ethernet2
    DC_LEAF3:
      bgp_as: 65103
      filter:
        tenants:
        - Tenant_blue
        - Tenant_green
        - Tenant_red
        tags:
        - blue_compute
        - blue_storage
        - green_storage
        - red_storage
      nodes:
        DC-LEAF3:
          id: 3
          mgmt_ip: 172.30.30.215/24
          spine_interfaces:
          - Ethernet3
          - Ethernet3
    DC_LEAF4:
      bgp_as: 65104
      filter:
        tenants:
        - Tenant_blue
        - Tenant_red
        tags:
        - blue_storage
        - red_storage
      nodes:
        DC-LEAF4:
          id: 4
          mgmt_ip: 172.30.30.216/24
          spine_interfaces:
          - Ethernet4
          - Ethernet4
spine_bgp_defaults:
- no bgp default ipv4-unicast
- distance bgp 20 200 200
- graceful-restart restart-time 300
- graceful-restart
leaf_bgp_defaults:
- no bgp default ipv4-unicast
- distance bgp 20 200 200
- graceful-restart restart-time 300
- graceful-restart
p2p_uplinks_mtu: 1500
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3
port_profiles:
  TENANT_BLUE_COMPUTE:
    mode: trunk
    vlans: '10'
  TENANT_BLUE_STORAGE:
    mode: trunk
    vlans: '50'
  TENANT_GREEN_COMPUTE:
    mode: trunk
    vlans: '20'
  TENANT_GREEN_STORAGE:
    mode: trunk
    vlans: '30'
  TENANT_RED_STORAGE:
    mode: trunk
    vlans: '40'
servers:
  server01:
    rack: RackA
    adapters:
    - type: nic
      server_ports:
      - E1
      - E2
      switch_ports:
      - Ethernet5
      - Ethernet5
      switches:
      - DC-LEAF1
      - DC-LEAF2
      profile: TENANT_BLUE_COMPUTE
      port_channel:
        description: PortChannel
        mode: active
        short_esi: 0001:1010:1010
  server02:
    rack: RackA
    adapters:
    - type: nic
      server_ports:
      - E1
      - E2
      switch_ports:
      - Ethernet6
      - Ethernet6
      switches:
      - DC-LEAF1
      - DC-LEAF2
      profile: TENANT_GREEN_COMPUTE
      port_channel:
        description: PortChannel
        mode: active
        short_esi: 0002:2020:2020
  server03:
    rack: RackA
    adapters:
    - type: nic
      server_ports:
      - E1
      - E2
      - E3
      switch_ports:
      - Ethernet7
      - Ethernet7
      - Ethernet7
      switches:
      - DC-LEAF1
      - DC-LEAF2
      - DC-LEAF3
      profile: TENANT_GREEN_STORAGE
      port_channel:
        description: PortChannel
        mode: active
        short_esi: 0003:3030:3030
  server04:
    rack: RackB
    adapters:
    - type: nic
      server_ports:
      - E1
      - E2
      switch_ports:
      - Ethernet8
      - Ethernet8
      switches:
      - DC-LEAF2
      - DC-LEAF3
      profile: TENANT_BLUE_COMPUTE
      port_channel:
        description: PortChannel
        mode: active
        short_esi: 0001:1111:1111
  server05:
    rack: RackB
    adapters:
    - type: nic
      server_ports:
      - E1
      - E2
      switch_ports:
      - Ethernet5
      - Ethernet5
      switches:
      - DC-LEAF3
      - DC-LEAF4
      profile: TENANT_RED_STORAGE
      port_channel:
        description: PortChannel
        mode: active
        short_esi: 0004:4040:4040
  server06:
    rack: RackB
    adapters:
    - type: nic
      server_ports:
      - E1
      - E2
      switch_ports:
      - Ethernet6
      - Ethernet6
      switches:
      - DC-LEAF3
      - DC-LEAF4
      profile: TENANT_BLUE_STORAGE
      port_channel:
        description: PortChannel
        mode: active
        short_esi: 0005:5050:5050
tenants:
  Tenant_blue:
    mac_vrf_vni_base: 10000
    vrfs:
      Tenant_blue_vrf:
        vrf_vni: 100
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          10:
            name: Tenant_blue_compute
            tags:
            - blue_compute
            enabled: true
            ip_address_virtual: 10.10.10.1/24
          50:
            name: Tenant_blue_storage
            tags:
            - blue_storage
            enabled: true
            ip_address_virtual: 10.10.50.1/24
  Tenant_green:
    mac_vrf_vni_base: 20000
    vrfs:
      Tenant_green_vrf:
        vrf_vni: 200
        vtep_diagnostic:
          loopback: 200
          loopback_ip_range: 10.255.2.0/24
        svis:
          20:
            name: Tenant_green_compute
            tags:
            - green_compute
            enabled: true
            ip_address_virtual: 10.10.20.1/24
          30:
            name: Tenant_green_storage
            tags:
            - green_storage
            enabled: true
            ip_address_virtual: 10.10.30.1/24
  Tenant_red:
    mac_vrf_vni_base: 30000
    vrfs:
      Tenant_red_vrf:
        vrf_vni: 300
        svis:
          40:
            name: Tenant_red_storage
            tags:
            - red_storage
            enabled: true
            ip_address_virtual: 10.10.40.1/24
type: l3leaf
inventory_file: /Users/daniel.tudares/Projects/cvp_evpn_vxlan_demo/inventory/inventory.yml
inventory_dir: /Users/daniel.tudares/Projects/cvp_evpn_vxlan_demo/inventory
ansible_host: 172.30.30.215
inventory_hostname: DC-LEAF3
inventory_hostname_short: DC-LEAF3
group_names:
- DC
- DC_FABRIC
- DC_L3LEAFS
- DC_LEAF3
- DC_SERVERS
- DC_TENANTS_NETWORKS
ansible_facts:
  switch:
    underlay_routing_protocol: ebgp
    overlay_routing_protocol: ebgp
    group: DC_LEAF3
    id: 3
    mgmt_ip: 172.30.30.215/24
    platform: vEOS-LAB
    platform_settings:
      platforms:
      - default
      reload_delay:
        mlag: 300
        non_mlag: 330
    configure_tenants: true
    filter_tenants:
    - Tenant_blue
    - Tenant_green
    - Tenant_red
    igmp_snooping_enabled: true
    filter_tags:
    - blue_compute
    - blue_storage
    - green_storage
    - red_storage
    max_spines: 2
    uplink_switches:
    - DC-SPINE1
    - DC-SPINE2
    uplink_switch_interfaces:
    - Ethernet3
    - Ethernet3
    uplink_interfaces:
    - Ethernet1
    - Ethernet2
    router_id: 192.168.100.5
    loopback_network_summary: 192.168.100.0/24
    bgp_as: 65103
    bgp_defaults:
    - no bgp default ipv4-unicast
    - distance bgp 20 200 200
    - graceful-restart restart-time 300
    - graceful-restart
    virtual_router_mac_address: 00:1c:73:00:dc:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    mlag_ibgp_origin_incomplete: true
    mlag: false
    vtep_ip: 192.168.101.5
    evpn_services_l2_only: false
    evpn_role: client
    evpn_route_servers:
    - DC-SPINE1
    - DC-SPINE2
    isis_net: 49.0001.0001.0001.0003.00
    tenants:
      Tenant_blue:
        vrfs:
          Tenant_blue_vrf:
            svis:
            - 10
            - 50
        l2vlans: []
      Tenant_green:
        vrfs:
          Tenant_green_vrf:
            svis:
            - 30
        l2vlans: []
      Tenant_red:
        vrfs:
          Tenant_red_vrf:
            svis:
            - 40
        l2vlans: []
    vlans:
    - 10
    - 50
    - 30
    - 40
  topology:
    links:
      Ethernet1:
        peer: DC-SPINE1
        peer_interface: Ethernet3
        peer_type: spine
        peer_bgp_as: 65100
        type: underlay_p2p
        ip_address: 10.10.100.9
        peer_ip_address: 10.10.100.8
      Ethernet2:
        peer: DC-SPINE2
        peer_interface: Ethernet3
        peer_type: spine
        peer_bgp_as: 65100
        type: underlay_p2p
        ip_address: 10.10.100.11
        peer_ip_address: 10.10.100.10
    peers:
    - DC-SPINE1
    - DC-SPINE2
switch:
  underlay_routing_protocol: ebgp
  overlay_routing_protocol: ebgp
  group: DC_LEAF3
  id: 3
  mgmt_ip: 172.30.30.215/24
  platform: vEOS-LAB
  platform_settings:
    platforms:
    - default
    reload_delay:
      mlag: 300
      non_mlag: 330
  configure_tenants: true
  filter_tenants:
  - Tenant_blue
  - Tenant_green
  - Tenant_red
  igmp_snooping_enabled: true
  filter_tags:
  - blue_compute
  - blue_storage
  - green_storage
  - red_storage
  max_spines: 2
  uplink_switches:
  - DC-SPINE1
  - DC-SPINE2
  uplink_switch_interfaces:
  - Ethernet3
  - Ethernet3
  uplink_interfaces:
  - Ethernet1
  - Ethernet2
  router_id: 192.168.100.5
  loopback_network_summary: 192.168.100.0/24
  bgp_as: 65103
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  virtual_router_mac_address: 00:1c:73:00:dc:01
  spanning_tree_mode: mstp
  spanning_tree_priority: 4096
  mlag_ibgp_origin_incomplete: true
  mlag: false
  vtep_ip: 192.168.101.5
  evpn_services_l2_only: false
  evpn_role: client
  evpn_route_servers:
  - DC-SPINE1
  - DC-SPINE2
  isis_net: 49.0001.0001.0001.0003.00
  tenants:
    Tenant_blue:
      vrfs:
        Tenant_blue_vrf:
          svis:
          - 10
          - 50
      l2vlans: []
    Tenant_green:
      vrfs:
        Tenant_green_vrf:
          svis:
          - 30
      l2vlans: []
    Tenant_red:
      vrfs:
        Tenant_red_vrf:
          svis:
          - 40
      l2vlans: []
  vlans:
  - 10
  - 50
  - 30
  - 40
topology:
  links:
    Ethernet1:
      peer: DC-SPINE1
      peer_interface: Ethernet3
      peer_type: spine
      peer_bgp_as: 65100
      type: underlay_p2p
      ip_address: 10.10.100.9
      peer_ip_address: 10.10.100.8
    Ethernet2:
      peer: DC-SPINE2
      peer_interface: Ethernet3
      peer_type: spine
      peer_bgp_as: 65100
      type: underlay_p2p
      ip_address: 10.10.100.11
      peer_ip_address: 10.10.100.10
  peers:
  - DC-SPINE1
  - DC-SPINE2
playbook_dir: /Users/daniel.tudares/Projects/cvp_evpn_vxlan_demo/playbooks/cvp
ansible_playbook_python: /Users/daniel.tudares/Projects/cvp_evpn_vxlan_demo/.venv/bin/python
ansible_config_file: /Users/daniel.tudares/Projects/cvp_evpn_vxlan_demo/ansible.cfg
groups:
  all:
  - CVP-ZTP
  - CVP-SERVER
  - DC-SPINE1
  - DC-SPINE2
  - DC-LEAF1
  - DC-LEAF2
  - DC-LEAF3
  - DC-LEAF4
  ungrouped: []
  CVP:
  - CVP-ZTP
  - CVP-SERVER
  DC:
  - DC-SPINE1
  - DC-SPINE2
  - DC-LEAF1
  - DC-LEAF2
  - DC-LEAF3
  - DC-LEAF4
  DC_FABRIC:
  - DC-SPINE1
  - DC-SPINE2
  - DC-LEAF1
  - DC-LEAF2
  - DC-LEAF3
  - DC-LEAF4
  DC_SPINES:
  - DC-SPINE1
  - DC-SPINE2
  DC_L3LEAFS:
  - DC-LEAF1
  - DC-LEAF2
  - DC-LEAF3
  - DC-LEAF4
  DC_LEAF1:
  - DC-LEAF1
  DC_LEAF2:
  - DC-LEAF2
  DC_LEAF3:
  - DC-LEAF3
  DC_LEAF4:
  - DC-LEAF4
  DC_TENANTS_NETWORKS:
  - DC-LEAF1
  - DC-LEAF2
  - DC-LEAF3
  - DC-LEAF4
  DC_SERVERS:
  - DC-LEAF1
  - DC-LEAF2
  - DC-LEAF3
  - DC-LEAF4
omit: __omit_place_holder__566106dbf00a79e465bdb912d6d8e8f899a185f4
ansible_version:
  string: 2.10.13
  full: 2.10.13
  major: 2
  minor: 10
  revision: 13
ansible_check_mode: false
ansible_diff_mode: false
ansible_forks: 5
ansible_inventory_sources:
- /Users/daniel.tudares/Projects/cvp_evpn_vxlan_demo/inventory/inventory.yml
ansible_skip_tags: []
ansible_run_tags:
- generate
ansible_verbosity: 0
