---
port_profiles:
  TENANT_BLUE_COMPUTE:
    mode: trunk
    vlans: "10"
  TENANT_BLUE_STORAGE:
    mode: trunk
    vlans: "50"
  TENANT_GREEN_COMPUTE:
    mode: trunk
    vlans: "20"
  TENANT_GREEN_STORAGE:
    mode: trunk
    vlans: "30"
  TENANT_RED_STORAGE:
    mode: trunk
    vlans: "40"

servers:
  server01:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [E1, E2]
        switch_ports: [Ethernet5, Ethernet5]
        switches: [DC-LEAF1, DC-LEAF2]
        profile: TENANT_BLUE_COMPUTE
        port_channel:
          description: PortChannel
          mode: active
          short_esi: 0001:1010:1010
  server02:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [E1, E2]
        switch_ports: [Ethernet6, Ethernet6]
        switches: [DC-LEAF1, DC-LEAF2]
        profile: TENANT_GREEN_COMPUTE
        port_channel:
          description: PortChannel
          mode: active
          short_esi: 0002:2020:2020
  server03:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [E1, E2, E3]
        switch_ports: [Ethernet7, Ethernet7, Ethernet7]
        switches: [DC-LEAF1, DC-LEAF2, DC-LEAF3]
        profile: TENANT_GREEN_STORAGE
        port_channel:
          description: PortChannel
          mode: active
          short_esi: 0003:3030:3030
  server04:
    rack: RackB
    adapters:
      - type: nic
        server_ports: [E1, E2]
        switch_ports: [Ethernet8, Ethernet8]
        switches: [DC-LEAF2, DC-LEAF3]
        profile: TENANT_BLUE_COMPUTE
        port_channel:
          description: PortChannel
          mode: active
          short_esi: 0001:1111:1111
  server05:
    rack: RackB
    adapters:
      - type: nic
        server_ports: [E1, E2]
        switch_ports: [Ethernet5, Ethernet5]
        switches: [DC-LEAF3, DC-LEAF4]
        profile: TENANT_RED_STORAGE
        port_channel:
          description: PortChannel
          mode: active
          short_esi: 0004:4040:4040
  server06:
    rack: RackB
    adapters:
      - type: nic
        server_ports: [E1,E2]
        switch_ports: [Ethernet6, Ethernet6]
        switches: [DC-LEAF3, DC-LEAF4]
        profile: TENANT_BLUE_STORAGE
        port_channel:
          description: PortChannel
          mode: active
          short_esi: 0005:5050:5050
