---
all:
  children:
    CVP:
      hosts:
        CVP-ZTP:
          ansible_host: 172.30.30.252
          ansible_user: root
          ansible_password: 'arista123'
        CVP-SERVER:
          ansible_httpapi_host: 172.30.30.252
          ansible_host: 172.30.30.252
          ansible_user: cvpadmin
          ansible_password: arista123
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
          ansible_httpapi_port: 443
          # Configuration to get Virtual Env information
          ansible_python_interpreter: $(which python3)
    DC:
      children:
        DC_FABRIC:
          children:
            DC_SPINES:
              hosts:
                DC-SPINE1:
                  ansible_host: 172.30.30.211
                DC-SPINE2:
                  ansible_host: 172.30.30.212
            DC_L3LEAFS:
              children:
                DC_LEAF1:
                  hosts:
                    DC-LEAF1:
                      ansible_host: 172.30.30.213
                DC_LEAF2:
                  hosts:
                    DC-LEAF2:
                      ansible_host: 172.30.30.214
                DC_LEAF3:
                  hosts:
                    DC-LEAF3:
                      ansible_host: 172.30.30.215
                DC_LEAF4:
                  hosts:
                    DC-LEAF4:
                      ansible_host: 172.30.30.216
          vars:
            ansible_connection: httpapi
            ansible_network_os: eos
            ansible_user: cvpadmin
            # should use vault for passwords
            ansible_ssh_pass: arista123
            ansible_become: true
            ansible_become_method: enable
            ansible_httpapi_use_ssl: true
            ansible_httpapi_validate_certs: false  
            # Configuration to get Virtual Env information
            ansible_python_interpreter: $(which python3)    
        DC_TENANTS_NETWORKS:
          children:
            DC_L3LEAFS:
        DC_SERVERS:
          children:
            DC_L3LEAFS:
